* DONE Make it so we can load a model directly from where we left off
  CLOSED: [2018-09-09 Sun 16:54]
* TODO Visualization tool for augmented data
* TODO Visualization tool for seeing the model's prediction on an image
* TODO Sacred added so we can keep track of each experiment's variations.
* TODO combine all data from the database into a single dataset.
* TODO Email notifications when an experiment run finishes
* TODO early termination for when VAL loss stagnates/gets worse.


* Later
** Rename the snakeoil file to something clearer
** Implement our own RL interface. 
** Auto-configure the view

  <section name="Display Mode">
    <section name="Player">
      <attnum name="camera" val="0"/>
      <attnum name="camera head list" val="0"/>
    </section>

    <section name="0">
      <attnum name="fovy-9-0" val="9"/>
    </section>

  </section>

BECOMES

  <section name="Display Mode">
    <section name="Player">
      <attnum name="camera" val="0"/>
      <attnum name="camera head list" val="0"/>
    </section>

    <section name="0">
      <attnum name="fovy-9-0" val="9"/>
      <attstr name="current driver" val="scr_server 1"/>
      <attnum name="camera" val="2"/>
      <attnum name="camera head list" val="0"/>
    </section>

  </section>
** Configure data generation tool
- How many frames? How many tracks?
** Stream data directly to an online-training model so that we can see it catch-up to expert skill in short time :)
** maintain the PID of the spawned torcs process so we can kill it.
** Make up your mind about accel vs throttle
